import assert from 'node:assert/strict';
import { splitTrainingDays as split } from './trainingDays.ts';
const exercise = title => ({title,description:''});
const divider = {type:'banner',text:'Flexibility 3x/week'};
const flag = {type:'banner',text:'Flag day',separateDay:true,dayId:'flag',dayFrequency:'2x/week'};
const straight = {type:'banner',text:'Straight day',separateDay:true,dayId:'straight'};
const legacy = [exercise('Handstand'),divider,exercise('Stretch')];
assert.deepEqual(split(legacy)[0].items, legacy);
assert.equal(split(legacy).length,1);
const grouped=split([flag,exercise('Flag'),divider,exercise('Stretch'),straight,exercise('Straight')]);
assert.equal(grouped.length,2);
assert.deepEqual(grouped[0].items,[exercise('Flag'),divider,exercise('Stretch')]);
assert.equal(grouped[0].frequency,'2x/week');
assert.notEqual(grouped[0].key,grouped[1].key);
assert.deepEqual(grouped[1].items,[exercise('Straight')]);
assert.equal(split([exercise('Warmup'),flag,exercise('Flag')])[0].title,'General training');
assert.equal(split([flag,straight,exercise('Straight')]).length,2);
assert.equal(split([flag,exercise('Flag'),straight]).length,2);
assert.deepEqual(split([{...flag,separateDay:false},exercise('Flag')])[0].items,[{...flag,separateDay:false},exercise('Flag')]);
console.log('Passed: legacy programs, nested section dividers, independent day keys, leading exercises, empty days, and opt-out.');
