-- Coach review submissions
-- Stores paid-user progress video uploads separately from the coach video library.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.coach_review_submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  note text not null default '',
  status text not null default 'uploading',
  mux_upload_id text,
  mux_asset_id text,
  mux_playback_id text,
  mux_processing_status text,
  duration_seconds integer,
  file_name text,
  file_size_bytes bigint,
  mime_type text,
  submitted_at timestamptz,
  coach_note text,
  reviewed_by_email text,
  reviewed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint coach_review_submissions_status_check
    check (status in ('uploading', 'processing', 'submitted', 'reviewed', 'error')),
  constraint coach_review_submissions_duration_check
    check (duration_seconds is null or duration_seconds >= 0),
  constraint coach_review_submissions_file_size_check
    check (file_size_bytes is null or file_size_bytes >= 0),
  constraint coach_review_submissions_note_length_check
    check (char_length(note) <= 2000),
  constraint coach_review_submissions_coach_note_length_check
    check (coach_note is null or char_length(coach_note) <= 5000),
  constraint coach_review_submissions_error_message_length_check
    check (error_message is null or char_length(error_message) <= 2000)
);

comment on table public.coach_review_submissions is
  'User-submitted progress videos for coach review. Playback tokens are generated by API routes and are not stored here.';
comment on column public.coach_review_submissions.status is
  'Upload/review lifecycle: uploading, processing, submitted, reviewed, or error.';
comment on column public.coach_review_submissions.mux_playback_id is
  'Signed Mux playback ID for the submitted video. Do not expose without a short-lived playback token.';

create index if not exists coach_review_submissions_user_created_idx
  on public.coach_review_submissions (user_id, created_at desc);

create index if not exists coach_review_submissions_status_created_idx
  on public.coach_review_submissions (status, created_at desc);

create index if not exists coach_review_submissions_created_idx
  on public.coach_review_submissions (created_at desc);

create unique index if not exists coach_review_submissions_mux_upload_id_uidx
  on public.coach_review_submissions (mux_upload_id)
  where mux_upload_id is not null;

create unique index if not exists coach_review_submissions_mux_asset_id_uidx
  on public.coach_review_submissions (mux_asset_id)
  where mux_asset_id is not null;

create or replace function public.set_coach_review_submissions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_coach_review_submissions_updated_at
  on public.coach_review_submissions;

create trigger set_coach_review_submissions_updated_at
before update on public.coach_review_submissions
for each row
execute function public.set_coach_review_submissions_updated_at();

alter table public.coach_review_submissions enable row level security;

grant select, insert, update on public.coach_review_submissions to authenticated;

drop policy if exists "Users can view their own coach review submissions"
  on public.coach_review_submissions;
create policy "Users can view their own coach review submissions"
on public.coach_review_submissions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create their own coach review submissions"
  on public.coach_review_submissions;
create policy "Users can create their own coach review submissions"
on public.coach_review_submissions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Admins can view all coach review submissions"
  on public.coach_review_submissions;
create policy "Admins can view all coach review submissions"
on public.coach_review_submissions
for select
to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email', '')) = any (
    array['josh@anglemethod.com', 'morgan@anglemethod.com']
  )
);

drop policy if exists "Admins can update coach review submissions"
  on public.coach_review_submissions;
create policy "Admins can update coach review submissions"
on public.coach_review_submissions
for update
to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email', '')) = any (
    array['josh@anglemethod.com', 'morgan@anglemethod.com']
  )
)
with check (
  lower(coalesce(auth.jwt() ->> 'email', '')) = any (
    array['josh@anglemethod.com', 'morgan@anglemethod.com']
  )
);
